### ISSUE TITLE
Member newsletter

### ISSUE THREAD

**Issue by rantahar** [nordic-rse/NordicRSE-organization#1]
We should send a general announcement email to our members to keep then up to date and to remind them about the organization.

Our plan is to send this after the unconference and include the time of the first association meeting.

See the draft at https://hackmd.io/@nordic-rse/rJt9Z8Y_d.

**Comment by rantahar** [comment]
I'm looking for things to mention in the newsletter

**Comment by samumantha** [comment]
We could also add a reminder about adding different groups and people to the website map https://nordic-rse.org/map/ ?
